name:  route_hierarchical
description:  A client routing library for Dart
version: 0.4.15
authors:
- Justin Fagnani <justinfagnani@google.com>
- Pavel Jbanov <pavelj@google.com>
homepage: https://github.com/angular/route.dart

dependencies:
  browser: any
  logging: any

dev_dependencies:
  unittest: any
